name: Publish on GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build site
        run: |
          deno task build --location=https://e53.org/

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.7

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.3
